apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns
  namespace: ops
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns
            image: ghcr.io/eflee/r53-ddns
            imagePullPolicy: IfNotPresent
            env:
              - name: ZONE_ID   
                value: Z06392827G1HWA3QN458
              - name: FQDN
                value: ddns.elif.sh.
              - name: AWS_ACCESS_KEY_ID   
                valueFrom:
                  secretKeyRef:
                    name: ddns-aws-keys
                    key: access_key_id
                    optional: false
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom: 
                  secretKeyRef:
                    name: ddns-aws-keys
                    key: secret_access_key
                    optional: false         
          restartPolicy: OnFailure
