apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextdns
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nextdns
            image: busybox
            args:
            - /bin/sh
            - -c
            - wget -qO- https://link-ip.nextdns.io/b9253e/8436ed85a1a0e080
          restartPolicy: OnFailure
